version: '3'
services:
  
  mongo-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "mongo-db"
    volumes:
      - .:/app
      - /app/products/node_modules

  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "mongo-db"
    volumes:
      - .:/app
      - /app/users/node_modules

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    depends_on:
      - products
      - users
    ports:
      - "8000:8000"